sparaguai/urls.py
from django.conf.urls import url
from django.contrib import admin
from core.views import home, estabelecimento_detail, categoria_detail, busca

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^categoria/(?P<slug>[\w-]+)$', categoria_detail, name='categoria_detail'),
    url(r'^busca/', busca, name='busca'),
    url(r'^admin/', admin.site.urls),
]

src/comments/urls.py
from django.conf.urls import url

from .views import (
	comment_detail,
	comment_delete,
)

urlpatterns = [
	url(r'^(?P<id>\d+)/$', comment_detail, name='comment_detail'),
	url(r'^(?P<id>\d+)/delete/$', comment_delete, name='comment_delete'),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from src.core.views import home, estabelecimento_detail, categoria_detail, categorias, busca


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    url(r'^$', home, name='home'),
    url(r'^busca/$', busca, name='busca'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^estabelecimento/$', home, name='estabelecimentos'),
    url(r'^categorias/$', categorias, name='categorias'),
    url(r'^api/', include('src.api.urls', namespace='api')),
    url(r'^tickets/', include('src.tickets.urls', namespace='tickets')),
    url(r'^noticia/', include('src.posts.urls', namespace='noticias')),
    url(r'^newsletters/', include('src.newsletters.urls', namespace='newsletters')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^categorias/(?P<slug>[\w-]+)/$', categoria_detail, name='categoria_detail'),

    # url(r'^password/change/$',
    #     auth_views.password_change,
    #     name='password_change'),
    # url(r'^password/change/done/$',
    #     auth_views.password_change_done,
    #     name='password_change_done'),
    # url(r'^password/reset/$',
    #     auth_views.password_reset,
    #     name='password_reset'),
    # url(r'^password/reset/done/$',
    #     auth_views.password_reset_done,
    #     name='password_reset_done'),
    # url(r'^password/reset/complete/$',
    #     auth_views.password_reset_complete,
    #     name='password_reset_complete'),
    # url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     auth_views.password_reset_confirm,
    #     name='password_reset_confirm'),
    # url(r'^accounts/profile/(?P<pk>[0-9]+)/update/$', UserProfileUpdate.as_view(), name='user_profile_update'),
    # url(r'^accounts/profile/(?P<slug>[\w-]+)/$', UserProfileDetail.as_view(), name='user_profile'),
    # url(r'^accounts/profile/$', profile, name='my_user_profile'),
    # url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    # url(r'^accounts/login/$', login, name='auth_login'),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--


    url(r'^admin/', admin.site.urls),

]

src/comments/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import ugettext_lazy as _
from star_ratings.models import UserRating


class CommentManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(aprovado=True)
        return qs

User = settings.AUTH_USER_MODEL


class Comment(models.Model):
    user = models.ForeignKey(User)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    content = models.TextField(_('Conteudo'))
    timestamp = models.DateTimeField(auto_now_add=True)
    aprovado = models.BooleanField(default=False)

    objects = CommentManager()

    def __str__(self):
        return self.user.username

    def get_rate(self):
        return UserRating.objects.for_instance_by_user(self.content_object, user=self.user).score

src/comments/forms.py
from django import forms
from django.utils.translation import ugettext as _


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    content = forms.CharField(
        label='',
        help_text=_('Escreva seu comentario'),
        required=True,
        widget=forms.Textarea(
            attrs={'rows': 5, 'cols': 40, 'placeholder': _('Escreva seu comentario'), 'class': 'form-control'})
    )


class CommentFormWithRate(CommentForm):
    nota = forms.IntegerField(widget=forms.HiddenInput, required=True)

src/comments/views.py
from django.shortcuts import render

# Create your views here.

src/comments/templates/comments/comment-form.html
{% load i18n %}
{% load static %}
{% if request.user.is_authenticated %}
    <style>
        #estrela_form .star-ratings-rating-full, #estrela_form .star-ratings-rating-empty {
            width: 28px;
            height: 28px;
            background: url({% static 'star-ratings/images/stars.png' %}) no-repeat;
            background-size: 84px;
        }

        #estrela_form .star-ratings-rating-empty {
            background-position: -28px 0;
        }


    </style>

    
    <div class="row">
       <form action="{{ url }}" method="POST">
           {% csrf_token %}
           
           <div class="col-sm-12"><h4>{% trans 'DÊ SUA NOTA' %}</h4></div>
           <div class="col-sm-2">
               <div id="estrela_form" class="star-ratings text-center" data-max-rating="5" data-avg-rating="1,000">
                   <div class="star-ratings-rating-stars-container">
                       <ul class="star-ratings-rating-background" >
                           {% for star in stars %}
                               <li>
                                   {% if user.is_authenticated  %}
                                       <span onclick="update_nota({{ star }})" onmouseover="update_nota_layout({{ star }})"
                                             onmouseleave="update_nota_layout(0)" class="star-ratings-rating-empty"></span>
                                   {% else %}
                                       <span class="star-ratings-rating-empty" title="{% trans 'Log in to rate' as title_login %}{{ title_login|escape }}"></span>
                                   {% endif %}
                               </li>
                           {% endfor %}
                       </ul>
                       <ul class="star-ratings-rating-foreground" >
                           <li><span id="nota_1" onclick="update_nota(1)" onmouseover="update_nota_layout(1)"
                                     onmouseleave="update_nota_layout(0)" class="star-ratings-rating-full"></span></li>
                           <li><span id="nota_2" onclick="update_nota(2)" onmouseover="update_nota_layout(2)"
                                     onmouseleave="update_nota_layout(0)" class="star-ratings-rating-full" style="display: none;"></span></li>
                           <li><span id="nota_3" onclick="update_nota(3)" onmouseover="update_nota_layout(3)"
                                     onmouseleave="update_nota_layout(0)" class="star-ratings-rating-full" style="display: none;"></span></li>
                           <li><span id="nota_4" onclick="update_nota(4)" onmouseover="update_nota_layout(4)"
                                     onmouseleave="update_nota_layout(0)" class="star-ratings-rating-full" style="display: none;"></span></li>
                           <li><span id="nota_5" onclick="update_nota(5)" onmouseover="update_nota_layout(5)"
                                     onmouseleave="update_nota_layout(0)" class="star-ratings-rating-full" style="display: none;"></span></li>
                       </ul>

                   </div>
               </div>

               {% if request.user.profile.avatar_normal %}
                   <img src="{{ request.user.profile.avatar_normal }}" width='100%' class='radius text-center' alt="">
               {% else %}
                   <img src="{% static 'img/avatar-holder.png' %}" width='100%' class='radius text-center'  alt="">
               {% endif %}
               <p class="text-center"><b>Nome do usuário</b></p>
           </div>
           <div class="col-sm-10">

               {{ form.content_type }}
               {{ form.object_id }}

               <div class='form-group'>

                   <label>Comentário</label>
                   {{ form.content }}
               </div>
               <input id="id_nota" name="nota" type="hidden" value="1">
               <input type="submit" value="{% trans 'Publicar' %}" class="btn pull-right">
           </div>
          
       </form> 
    </div>

    
    <script>

        function update_nota_layout(nota) {
            if (nota > 0) {
                for (var i = 1; i <= 5; i++) {
                    if (i > nota) {
                        $('#nota_'+i).hide();
                    }
                    else {
                        $('#nota_' + i).show();
                    }
                }
            }else {
                nota = parseInt($('#id_nota').val());
                for (var i = 5; i > 0; i--) {
                    if (i > nota) {
                        $('#nota_'+i).hide();
                    }
                    else {
                        $('#nota_' + i).show();
                    }
                }
            }

        }

        function update_nota(nota) {
            $("#id_nota").val(nota);
            {#        console.log($('#id_nota').val());#}
        }


    </script>
{% else %}
    <p class="text-center">{% trans 'Voce precisa estar logado para comentar.' %}
        <br>
        <a href="{% url 'social:begin' 'facebook' %}">{% trans 'Entre aqui.' %}</a>
    </p>
{% endif %}

src/comments/templates/comments/comments.html
{% load i18n %}
{% load ratings %}
{% load static %}

<div class="row" id="comments">
    <div class="col-md-12">
        <div class="header-comentarios">
            <h3>{% trans 'Avaliações & Comentários' %}</h3>
        </div>
        <div class="body-comentarios">
            {% for comment in comments %}
                <div class="comment">
                    <div class="user-photo">
                        {% if comment.user.profile.avatar_normal %}
                            <img src="{{comment.user.profile.avatar_normal}}" class="radius" alt="">
                        {% else %}
                            <img src="{% static 'img/avatar-holder.png' %}" width="60" alt="">
                        {% endif %}
                    </div>
                    <div class="user-content">
                        <p class="name">{{ comment.user }}</p>
                        <p class="date">{{ comment.timestamp|timesince }} atrás</p>
                        {% include 'core/widgets/star.html' with total=comment.get_rate %}
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="content">
                        <br>
                        <p>{{ comment.content }}</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            {% endfor %}
        </div>
        
    </div>
    
    <div class="col-md-12">
        <div class="body-comentarios">
            {% include 'comments/comment-form.html' with form=form url=estabelecimento.get_absolute_url %}
        </div>
    </div>
    

    
</div>
<div class="row">
    {% if comments.paginator.num_pages > 1 %}
        <ul class="pagination">
            {% with ''|center:comments.paginator.num_pages as range %}
                {% for _ in range %}
                    <li{% if forloop.counter == comments.number %} class="active"{% endif %}><a href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                {% endfor %}
            {% endwith %}
        </ul>
    {% endif %}
</div>