sparaguai/urls.py
from django.conf.urls import url
from django.contrib import admin
from core.views import home, estabelecimento_detail, categoria_detail, busca

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^categoria/(?P<slug>[\w-]+)$', categoria_detail, name='categoria_detail'),
    url(r'^busca/', busca, name='busca'),
    url(r'^admin/', admin.site.urls),
]

src/tickets/urls.py
from django.conf.urls import url

from src.tickets.views import anunciante, cadastrar_empresa

urlpatterns = [
    url(r'^seja-anunciante/$', anunciante, name='anunciante'),
    url(r'^cadastrar-empresa/$', cadastrar_empresa, name='cadastrar-empresa'),

]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from src.core.views import home, estabelecimento_detail, categoria_detail, categorias, busca


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    url(r'^$', home, name='home'),
    url(r'^busca/$', busca, name='busca'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^estabelecimento/$', home, name='estabelecimentos'),
    url(r'^categorias/$', categorias, name='categorias'),
    url(r'^api/', include('src.api.urls', namespace='api')),
    url(r'^tickets/', include('src.tickets.urls', namespace='tickets')),
    url(r'^noticia/', include('src.posts.urls', namespace='noticias')),
    url(r'^newsletters/', include('src.newsletters.urls', namespace='newsletters')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^categorias/(?P<slug>[\w-]+)/$', categoria_detail, name='categoria_detail'),

    # url(r'^password/change/$',
    #     auth_views.password_change,
    #     name='password_change'),
    # url(r'^password/change/done/$',
    #     auth_views.password_change_done,
    #     name='password_change_done'),
    # url(r'^password/reset/$',
    #     auth_views.password_reset,
    #     name='password_reset'),
    # url(r'^password/reset/done/$',
    #     auth_views.password_reset_done,
    #     name='password_reset_done'),
    # url(r'^password/reset/complete/$',
    #     auth_views.password_reset_complete,
    #     name='password_reset_complete'),
    # url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     auth_views.password_reset_confirm,
    #     name='password_reset_confirm'),
    # url(r'^accounts/profile/(?P<pk>[0-9]+)/update/$', UserProfileUpdate.as_view(), name='user_profile_update'),
    # url(r'^accounts/profile/(?P<slug>[\w-]+)/$', UserProfileDetail.as_view(), name='user_profile'),
    # url(r'^accounts/profile/$', profile, name='my_user_profile'),
    # url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    # url(r'^accounts/login/$', login, name='auth_login'),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--


    url(r'^admin/', admin.site.urls),

]

src/core/models.py
# -*- coding: utf-8 -*-
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.shortcuts import resolve_url as r
from django.utils.translation import ugettext as _
from imagekit.models import ImageSpecField
from mptt.fields import TreeManyToManyField
from mptt.models import MPTTModel, TreeForeignKey
from pilkit.processors import ResizeToFit
from star_ratings.models import Rating, UserRating

from src.comments.models import Comment
from src.core.managers import AnuncioManager, EstabelecimentoManager, CategoriaManager
from src.core.utils import path_and_rename_logo, path_and_rename_fotos, path_and_rename_categoria, \
    path_and_rename_banner


class Estabelecimento(models.Model):

    CIDADES = (
        ('E', 'Ciudad del Este'),
        ('P', 'Pedro Juan Caballero'),
        ('S', 'Salto del Guairá'),

    )
    nome = models.CharField(max_length=120)
    recomendado = models.BooleanField(default=False, blank=True)
    website = models.URLField()
    slug = models.SlugField(unique=True)
    logo = models.ImageField(upload_to=path_and_rename_logo, null=True, help_text='### ATENÇÃO - TAMANHO DA IMAGEM PRECISA SER 310x294 ###')
    descricao = models.TextField()
    endereco = models.CharField(max_length=60)
    cidade = models.CharField(max_length=1, choices=CIDADES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    coordenadas = models.CharField('Coordenadas', null=True, blank=True, max_length=40)
    categoria = TreeManyToManyField('Categoria', blank=True, related_name='estabelecimentos')

    search_hits = models.PositiveIntegerField('Total de buscas acessadas', default=1)
    nota = GenericRelation(Rating, related_query_name='estabelecimentos')

    objects = EstabelecimentoManager()

    class Meta:
        verbose_name = 'Estabelecimento'
        verbose_name_plural = 'Estabelecimentos'
        ordering = ['nome']

    def __str__(self):
        return self.nome

    def get_average_rate(self):
        return Rating.objects.for_instance(self).average

    def get_coordenadas(self):
        if self.coordenadas:
            return self.coordenadas
        else:
            return "-25.513475,-54.615440"

    def get_latitude_longitde(self):
        return map(lambda x: float(x), self.coordenadas.split(','))

    def serializer(obj):
        latitude, longitude = obj.get_latitude_longitde()
        return dict(nome=obj.nome, latitude=latitude, longitude=longitude, categoria_icon=obj.get_categoria_icon())

    def get_absolute_url(self):
        return r('estabelecimento_detail', slug=self.slug)

    def get_categoria_icon(self):
        categoria_principal = None
        for categoria in self.categoria.all():
            if not categoria.parent == None:
                categoria_principal = categoria.parent
            else:
                categoria_principal = categoria
                break
        return categoria_principal.logo_thumbnail.url

    @property
    def is_hotel(self):
        return len(self.categoria.filter(nome__icontains=_('Hospedagem'))) > 0

    @property
    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)

    @staticmethod
    def get_cidade_index(cidade):
        if not cidade or 'todas' in cidade:
            return 'todas'
        for index, _cidade in Estabelecimento.CIDADES:
            if cidade in _cidade:
                return index
        return None


class Telefone(models.Model):
    estabelecimento = models.ForeignKey('Estabelecimento', related_name='telefones')
    numero = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        return self.numero


class Foto(models.Model):
    estabelecimento = models.ForeignKey('Estabelecimento')
    foto = models.ImageField(upload_to=path_and_rename_fotos, null=True, blank=True, help_text='### ATENÇÃO - TAMANHO DA IMAGEM PRECISA SER 800x800 ###')

    def __str__(self):
        return self.foto.name


class Categoria(MPTTModel):
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    nome = models.CharField(max_length=60)
    slug = models.SlugField()
    logo = models.ImageField(upload_to=path_and_rename_categoria, null=True, blank=True)
    logo_thumbnail = ImageSpecField(source='logo',
                                      processors=[ResizeToFit(32, 32)],
                                      format='PNG',
                                      options={'quality': 100})

    recomendado = models.BooleanField(default=False)

    objects = CategoriaManager()

    class MPTTMeta:
        order_insertion_by = ['nome']

    def __str__(self):
        return self.nome

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

    def get_absolute_url(self):
        return r('categoria_detail', slug=self.slug)


class Anuncio(models.Model):
    banner = models.ImageField(upload_to=path_and_rename_banner, help_text='### ATENÇÃO - TAMANHO DA IMAGEM PRECISA SER 585x80 ###')
    url = models.URLField()
    estabelecimento = models.ForeignKey('Estabelecimento', blank=True, null=True)
    ativo = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = AnuncioManager()

    def __str__(self):
        if self.estabelecimento:
            return self.estabelecimento.nome
        else:
            return self.url


class Caracteristica(models.Model):

    estabelecimento = models.ForeignKey('Estabelecimento',related_name='caracteristicas')
    titulo = models.CharField(max_length=100)
    conteudo = models.CharField(max_length=250)

    def __str__(self):
        return self.titulo


class Preco(models.Model):
    estabelecimento = models.ForeignKey('Estabelecimento', related_name='precos')
    titulo = models.CharField(null=True, blank=True, max_length=100)
    valor = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return '{} - {}'.format(self.titulo, self.valor)

core/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

from core.models import Categoria, Estabelecimento


def home(request):
    context = {'nodes': Categoria.objects.all()}
    return render(request, 'index.html', context)


def estabelecimento_detail(request, slug):
    estabelecimento = get_object_or_404(Estabelecimento, slug=slug)
    return render(request, 'core/estabelecimento_detail.html', {'estabelecimento': estabelecimento})


def categoria_detail(request, slug):
    categoria = Categoria.objects.get(slug=slug)
    estabelecimentos = Estabelecimento.objects.filter(categoria=categoria)
    return render(request, 'core/categoria_detail.html', {'categoria': categoria})


def busca(request):
    context = {'estabelecimentos': None}
    if 's' in request.GET:
        context = {'estabelecimentos': Estabelecimento.objects.filter(nome__icontains=request.GET['s'])}

    return render(request, 'core/busca_resultado.html', context)

src/core/views.py
import urllib

from django.conf import settings
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, resolve_url
from django.utils.translation import ugettext as _
from star_ratings import app_settings
from star_ratings.models import Rating

from src.comments.forms import CommentForm, CommentFormWithRate
from src.comments.models import Comment
from src.core.models import Categoria, Estabelecimento, Anuncio
from src.posts.models import Post


def home(request):

    query_estabelecimento = Estabelecimento.objects.all()

    noticias = Post.objects.noticias().principais(2)
    lazer = Post.objects.lazer().principais(4)

    recomendados = Estabelecimento.objects.recomendados(12)

    mais_buscados = Estabelecimento.objects.mais_buscados(32)
    mais_buscados_recomendados = Estabelecimento.objects.mais_buscados().recomendados(8)
    anuncios = Anuncio.objects.ativos(2)

    categorias = Categoria.objects.recomendadas(6)

    context = {
        'estabelecimentos': query_estabelecimento,
        'noticias': noticias,
        'lazer': lazer,
        'recomendados': recomendados,
        'anuncios': anuncios,
        'mais_buscados': mais_buscados,
        'mais_buscados_recomendados': mais_buscados_recomendados,
        'categorias': categorias
    }
    return render(request, 'index.html', context)


def busca(request):
    cidades = [cidade[1] for cidade in Estabelecimento.CIDADES]

    cidade = request.GET.get('cidade', None)
    nome = request.GET.get('nome', None)
    preco = request.GET.get('preco', None)
    categoria = request.GET.get('categoria', None)
    cidade = Estabelecimento.get_cidade_index(cidade)
    valid_querystring = {k: v for k, v in request.GET.dict().items() if v}
    if valid_querystring != request.GET.dict():
        encoded_querystring = '?' + urllib.parse.urlencode(valid_querystring)
        return HttpResponseRedirect(resolve_url('home') + encoded_querystring)

    parametros = ''
    for item, value in request.GET.dict().items():
        if not item == 'page':
            parametros += '&{}={}'.format(item, value)
    parametros = parametros.replace(' ', '+')
    query_estabelecimento = Estabelecimento.objects.busca(cidade=cidade, nome=nome, preco=preco, categoria=categoria)

    paginator = Paginator(query_estabelecimento, settings.ESTABELECIMENTOS_POR_PAGINA)
    page = request.GET.get('page')
    try:
        query_estabelecimento = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_estabelecimento = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_estabelecimento = paginator.page(paginator.num_pages)

    anuncios = Anuncio.objects.ativos(count=1)

    context = {
        'estabelecimentos': query_estabelecimento,
        'cidades': cidades,
        'categorias': Categoria.objects.all(),
        'parametros': parametros,
        'anuncios': anuncios
    }
    return render(request, 'core/resultado_busca.html', context)


def estabelecimento_detail(request, slug):
    instance = get_object_or_404(Estabelecimento, slug=slug)
    log = request.GET.get('searchlog')
    if log:
        total_hits = instance.search_hits
        instance.search_hits = total_hits + 1
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

    template_to_render = 'core/estabelecimento_detail.html'
    if instance.is_hotel:
        template_to_render = 'core/hotel_detail.html'
    comments = instance.comments
    paginator = Paginator(comments, 6)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)

    initial_data = {
        'content_type': instance.get_content_type,
        'object_id': instance.id,
        'nota': 1
    }
    form = CommentFormWithRate(request.POST or None, initial=initial_data)

    if form.is_valid():
        c_type = form.cleaned_data.get('content_type').lower()
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get('content')
        new_comment = Comment.objects.filter(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
        ).first()
        if new_comment:
            new_comment.content = content_data
            new_comment.save()

        else:
            new_comment = Comment.objects.create(
                user=request.user,
                content_type=content_type,
                object_id=obj_id,
                content=content_data
            )
        nota = form.cleaned_data.get('nota')

        rating = instance.nota.rate(user=request.user, instance=instance, score=int(nota))
        new_comment.aprovado = False
        new_comment.save()
        # if created:
        #     form = CommentForm(None, initial=initial_data)
        #     messages.success(request, _('Seu comentário será moderado e adicionado em breve.'))
        messages.success(request, _('Seu comentário será moderado e adicionado em breve.'))
        form = CommentForm(None, initial=initial_data)

    stars = [i for i in range(1, app_settings.STAR_RATINGS_RANGE + 1)]
    rating = Rating.objects.for_instance(instance)

    context = {
        'estabelecimento': instance,
        'comments': comments,
        'form': form,
        'coordenadas': instance.get_coordenadas,
        'stars': stars,
        'rating': rating,
    }
    return render(request, template_to_render, context)


def categoria_detail(request, slug):
    try:
        categoria = Categoria.objects.get(slug=slug)
    except:
        raise Http404
    query_estabelecimento = Estabelecimento.objects.busca(categoria=categoria.nome)

    paginator = Paginator(query_estabelecimento, settings.ESTABELECIMENTOS_POR_PAGINA)
    page = request.GET.get('page')
    try:
        query_estabelecimento = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_estabelecimento = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_estabelecimento = paginator.page(paginator.num_pages)

    anuncios = Anuncio.objects.ativos(count=1)

    context = {
        'estabelecimentos': query_estabelecimento,
        'categorias': Categoria.objects.all(),
        'anuncios': anuncios
    }
    return render(request, 'core/resultado_busca.html', context)


def categorias(request):
    categorias = Categoria.objects.all()
    return render(request, 'core/categorias.html', {'categorias': categorias})

src/core/templates/core/widgets/busca.html
{% load i18n %}
<section id="busca">
    <div class="busca-body">
        <div class="container global-search">
            <div class="row">
                <form class="form-inline " action="/" method="get" role="form">
                    <div class="col-md-3">
                        <select name="cidade" class="select-input center" id="select-cidades">
                            <option value="" disabled selected>{% trans 'Cidade' %}</option>
                            <option value="todas">{% trans 'Todas' %}</option>
                            {% for cidade in cidades %}
                                <option value="{{ cidade }}">{{ cidade }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3">

                        <select name="categoria" class="select-input">
                            <option value="" disabled selected>{% trans 'Categoria' %}</option>
                            <option value="todas">{% trans 'Todas' %}</option>
                            {% for node in categorias %}
                                {% if node.is_child_node %}
                                    <option value="{{ node.nome }}">
                                        {{ node.parent }} :: {{ node }}
                                    </option>
                                {% endif %}

                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3">

                        <input type="search" class="form-control input-estabelecimento" id="s" name="nome" placeholder="{%  trans 'Nome Estabelecimento' %}">
                    </div>
                    <div class="col-md-3">
                        {#      <input type="text" class="form-control" placeholder="Search for...">#}
                        {#      <span class="input-group-btn">#}
                        {#        <button class="btn btn-secondary" type="button">Go!</button>#}
                        {#      </span>#}
                        {#    </div>#}
                        <input type="text" class=" input-preco form-control " name='preco' id="InputAmount" placeholder="{%  trans 'Preço' %}">
                        <label class="sr-only" for="InputAmount">{%  trans 'Preço' %}</label>
                        <button type="submit" id="s" class="btn btn-default submit-button"><span class="glyphicon glyphicon-search"></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

src/core/templates/core/widgets/carousel.html
<div class="row">
    <div class="container">
        <div id="carousel">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    {% for f in fotos %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" {% if forloop.counter0 == 0 %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>

                <!-- Wrapper for slides -->

                <div class="carousel-inner" role="listbox">
                    {% for foto in fotos %}
                        <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                            <img src="{{ foto.foto.url }}" alt="1">
                            <div class="carousel-caption">

                            </div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>

</div>

src/core/templates/core/widgets/descricao_estabelecimento.html
{% load i18n %}
{{ estabelecimento.descricao|linebreaks }}
<div class="clearfix"></div>
<br>
{% for tel in estabelecimento.telefones.all %}
    <h4> <i class="fa fa-phone"></i> {{ tel.numero }}</h4>
{% endfor %}
      

src/core/templates/core/widgets/estabelecimento_card.html
{% load ratings %}
{% load i18n %}
{% for e in estabelecimentos %}
    <div class="item">
        <a href="{{ e.get_absolute_url }}">
            <div class="img">
                {% if e.logo %}<img src="{{ e.logo.url }}" class="photo center" alt="">{% endif %}
            </div>
            <div class="caption">
                <div class="name">
                    {{ e.nome }}
                </div>
                {% include 'core/widgets/star.html' with total=e.get_average_rate %}
                <span>{{ e.descricao|truncatechars_html:120 }}{% trans '... Saiba Mais' %}</span>
                <div class="clearfix"></div>
                
            </div>
        </a>
    </div>
{% endfor %}

src/core/templates/core/widgets/form_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block  nav %}
    {% include 'nav-interno.html' %}
{% endblock %}

{% block content %}
	<main class="main">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
                    <div class="breadcrumbs">
                        <nav>
                            <a href="/">
                                Home
                            </a>

                            <a href="#">
                                Seja um anunciante
                            </a>
                           
                            
                        </nav>
                    </div>
                </div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h1>
					<h3>Molestiae, dolorem. Hic sequi aperiam voluptate veritatis, ad aliquid eius corporis ipsa rerum.</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius at dicta molestiae asperiores doloremque porro itaque totam, dolorem labore enim quae, fuga quod, sed ab voluptate suscipit officia alias obcaecati!</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, iure quo cupiditate eligendi doloribus voluptas labore reiciendis nesciunt eos beatae neque mollitia nostrum blanditiis, sequi excepturi qui impedit minus dolorum.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius at dicta molestiae asperiores doloremque porro itaque totam, dolorem labore enim quae, fuga quod, sed ab voluptate suscipit officia alias obcaecati!</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, iure quo cupiditate eligendi doloribus voluptas labore reiciendis nesciunt eos beatae neque mollitia nostrum blanditiis, sequi excepturi qui impedit minus dolorum.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius at dicta molestiae asperiores doloremque porro itaque totam, dolorem labore enim quae, fuga quod, sed ab voluptate suscipit officia alias obcaecati!</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, iure quo cupiditate eligendi doloribus voluptas labore reiciendis nesciunt eos beatae neque mollitia nostrum blanditiis, sequi excepturi qui impedit minus dolorum.</p>
				</div>
				<div class="col-md-6">
					<form method="POST">
					    {% csrf_token %}
					    {{ form|crispy }}
					    <button type="submit">{% trans 'Enviar' %}</button>
					</form>
				</div>
			</div>
			
		    
		</div>	
	</main>
    
{% endblock %}

src/core/templates/core/widgets/header-estabelecimento.html
{% load ratings %}
<div class="row">
    <div class="place">
        <div class="col-xs-12">
            <div class="breadcrumbs">
                <nav>
                    <a href="/">
                        Home
                    </a>
                    {% for categoria in estabelecimento.categoria.all %}
                        <a href="{{ categoria.get_absolute_url }}">{{ categoria.nome }}</a>
                    {% endfor %}
                </nav>
            </div>
        </div>
        <div class="col-xs-12">
            {% if messages %}
                <div class="alert alert-success alert-dismissable messages fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="col-xs-12">
            <h1 class="pull-left">{{ estabelecimento.nome }}</h1>
            <div class="pull-left">
                <div class="ratings">
                    {% include 'core/widgets/star.html' with total=estabelecimento.get_average_rate %}
                </div>
            </div>
        </div>
    </div>
</div>

src/core/templates/core/widgets/mapa-single.html
{% extends 'core/widgets/mapa.html' %}
{% block endereco-mapa %}
<div class="row col-md-12">
    <div class="venue">
        <div class="venue-address col-md-6 gutter">
            <p class="address">
                <i class="fa fa-2x fa-map-marker fa-inverse"></i>
                {{ estabelecimento.endereco }} <br>
                {{ estabelecimento.get_cidade_display }}
            </p>
        </div>
    </div>
</div>
{% endblock %}

src/core/templates/core/widgets/mapa.html
<div class="row">
    <div class="container">
        <div id="coordenadas"  data-coordenadas="{{ estabelecimento.coordenadas }}" style="display: none;"></div>
        <div id="map-canvas">
            <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" ></iframe><br />
        </div>
        {% block endereco-mapa %}{% endblock %}
    </div>
</div>

src/core/templates/core/widgets/messages_display.html
<div class="col-xs-12" style="margin:10px 0;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissable messages fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

src/core/templates/core/widgets/nav-base.html
{% load i18n %}
<div class="topbar">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <nav class="social-nav pull-left">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-envelope"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-youtube"></i></a>
                </nav>
            </div>
            <div class="col-md-6">
                <nav class="top-menu pull-right">
                    {#<a href="{% url 'tickets:cadastrar-empresa' %}">{% trans 'Cadastrar minha empresa' %}</a>#}
                    {#<a href="#">{% trans 'Tour 360º' %}</a>#}
                    <a href="#">{% trans 'Temperatura em Ciudad del Este:' %} <span class="weather">{% trans 'Buscando...' %}</span></a>
                    <a href="{% url 'tickets:anunciante' %}">{% trans 'Seja um anunciante' %}</a>
                </nav>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

src/core/templates/core/widgets/star.html
{% load i18n %}
{% load static %}
<style>
    #custom_form .star-ratings-rating-full, #custom_form .star-ratings-rating-empty {
        width: 28px;
        height: 28px;
        background: url({% static 'star-ratings/images/stars.png' %}) no-repeat;
        background-size: 84px;
    }

    #custom_form .star-ratings-rating-empty {
        background-position: -28px 0;
    }


</style>
<div id="custom_form" class="star-ratings" data-max-rating="{{ total }}" data-avg-rating="{{ total }}">
    <div class="star-ratings-rating-stars-container">
        <ul class="star-ratings-rating-background" >
                <li><span class="star-ratings-rating-empty"></span></li>
                <li><span class="star-ratings-rating-empty"></span></li>
                <li><span class="star-ratings-rating-empty"></span></li>
                <li><span class="star-ratings-rating-empty"></span></li>
                <li><span class="star-ratings-rating-empty"></span></li>
        </ul>
        <ul class="star-ratings-rating-foreground" >
            {% for star in "01234" %}
                {% if forloop.counter0 < total %}
                    <li><span class="star-ratings-rating-full"></span></li>
                {% endif %}
            {% endfor %}
        </ul>

    </div>
</div>