sparaguai/urls.py
from django.conf.urls import url
from django.contrib import admin
from core.views import home, estabelecimento_detail, categoria_detail, busca

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^categoria/(?P<slug>[\w-]+)$', categoria_detail, name='categoria_detail'),
    url(r'^busca/', busca, name='busca'),
    url(r'^admin/', admin.site.urls),
]

src/posts/urls.py
from django.conf.urls import url

from src.posts.views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from src.core.views import home, estabelecimento_detail, categoria_detail, categorias, busca


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    url(r'^$', home, name='home'),
    url(r'^busca/$', busca, name='busca'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^estabelecimento/$', home, name='estabelecimentos'),
    url(r'^categorias/$', categorias, name='categorias'),
    url(r'^api/', include('src.api.urls', namespace='api')),
    url(r'^tickets/', include('src.tickets.urls', namespace='tickets')),
    url(r'^noticia/', include('src.posts.urls', namespace='noticias')),
    url(r'^newsletters/', include('src.newsletters.urls', namespace='newsletters')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^categorias/(?P<slug>[\w-]+)/$', categoria_detail, name='categoria_detail'),

    # url(r'^password/change/$',
    #     auth_views.password_change,
    #     name='password_change'),
    # url(r'^password/change/done/$',
    #     auth_views.password_change_done,
    #     name='password_change_done'),
    # url(r'^password/reset/$',
    #     auth_views.password_reset,
    #     name='password_reset'),
    # url(r'^password/reset/done/$',
    #     auth_views.password_reset_done,
    #     name='password_reset_done'),
    # url(r'^password/reset/complete/$',
    #     auth_views.password_reset_complete,
    #     name='password_reset_complete'),
    # url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     auth_views.password_reset_confirm,
    #     name='password_reset_confirm'),
    # url(r'^accounts/profile/(?P<pk>[0-9]+)/update/$', UserProfileUpdate.as_view(), name='user_profile_update'),
    # url(r'^accounts/profile/(?P<slug>[\w-]+)/$', UserProfileDetail.as_view(), name='user_profile'),
    # url(r'^accounts/profile/$', profile, name='my_user_profile'),
    # url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    # url(r'^accounts/login/$', login, name='auth_login'),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--


    url(r'^admin/', admin.site.urls),

]

src/posts/models.py
from __future__ import unicode_literals

from random import randint

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Count
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown

from src.comments.models import Comment
from src.posts.utils import get_read_time


class PostManagerQuerySet(models.QuerySet):
    def active(self):
        return self.filter(draft=False).filter(publish__lte=timezone.now())

    def noticias(self):
        return self.active().filter(type=0).order_by('-timestamp')

    def lazer(self):
        return self.active().filter(type=1).order_by('-timestamp')

    def principais(self, count=None):
        total = self.count()
        if total == 0:
            return []
        if not count:
            return self.order_by('-timestamp')
        elif count > total:
            dif = count - total
            principais = list(self.all().order_by('-timestamp'))
            while dif > 0:
                index = self.aggregate(count=Count('id'))['count']
                random_index = randint(0, index - 1)
                principais.append(self.all()[random_index])
                dif -= 1

            return principais
        else:
            return self.order_by('-timestamp')[:count]


PostManager = models.Manager.from_queryset(PostManagerQuerySet)

TIPO_POST_CHOICES = getattr(settings, 'TIPO_POST_CHOICES', (
    (0, ("Noticia")),
    (1, ("Lazer Turismo")),
))


def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    # return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    # new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" % (instance.slug, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              help_text='### ATENÇÃO - TAMANHO DA IMAGEM PRECISA SER 555x235 NOTICIA OU 265x360 PARA LAZER / TURISMO ###'
                              )
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    type = models.SmallIntegerField(("categoria"), choices=TIPO_POST_CHOICES, default=0)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("noticias:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs

    @property
    def get_content_type(self):
        qs = ContentType.objects.get_for_model(self.__class__)
        return qs


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time

# before save a post this signal is triggered
pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from pagedown.widgets import PagedownWidget
from django import forms


from src.posts.models import Post


class PostForm(forms.ModelForm):

    title = forms.CharField(label='Titulo')
    content = forms.CharField(label='Conteudo', widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(label='Publicar em', widget=forms.SelectDateWidget)
    image = forms.ImageField(label='Capa do post', required=True, help_text='TAMANHO DA IMAGEM PRECISA SER 555x235 PARA NOTICIA OU 265x360 PARA LAZER / TURISMO')
    draft = forms.BooleanField(label='Rascunho', required=False)
    # type = forms.IntegerField(label='Categoria')

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            'type',
            "image",
            "draft",
            "publish",
        ]

core/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

from core.models import Categoria, Estabelecimento


def home(request):
    context = {'nodes': Categoria.objects.all()}
    return render(request, 'index.html', context)


def estabelecimento_detail(request, slug):
    estabelecimento = get_object_or_404(Estabelecimento, slug=slug)
    return render(request, 'core/estabelecimento_detail.html', {'estabelecimento': estabelecimento})


def categoria_detail(request, slug):
    categoria = Categoria.objects.get(slug=slug)
    estabelecimentos = Estabelecimento.objects.filter(categoria=categoria)
    return render(request, 'core/categoria_detail.html', {'categoria': categoria})


def busca(request):
    context = {'estabelecimentos': None}
    if 's' in request.GET:
        context = {'estabelecimentos': Estabelecimento.objects.filter(nome__icontains=request.GET['s'])}

    return render(request, 'core/busca_resultado.html', context)

src/core/views.py
import urllib

from django.conf import settings
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, resolve_url
from django.utils.translation import ugettext as _
from star_ratings import app_settings
from star_ratings.models import Rating

from src.comments.forms import CommentForm, CommentFormWithRate
from src.comments.models import Comment
from src.core.models import Categoria, Estabelecimento, Anuncio
from src.posts.models import Post


def home(request):

    query_estabelecimento = Estabelecimento.objects.all()

    noticias = Post.objects.noticias().principais(2)
    lazer = Post.objects.lazer().principais(4)

    recomendados = Estabelecimento.objects.recomendados(12)

    mais_buscados = Estabelecimento.objects.mais_buscados(32)
    mais_buscados_recomendados = Estabelecimento.objects.mais_buscados().recomendados(8)
    anuncios = Anuncio.objects.ativos(2)

    categorias = Categoria.objects.recomendadas(6)

    context = {
        'estabelecimentos': query_estabelecimento,
        'noticias': noticias,
        'lazer': lazer,
        'recomendados': recomendados,
        'anuncios': anuncios,
        'mais_buscados': mais_buscados,
        'mais_buscados_recomendados': mais_buscados_recomendados,
        'categorias': categorias
    }
    return render(request, 'index.html', context)


def busca(request):
    cidades = [cidade[1] for cidade in Estabelecimento.CIDADES]

    cidade = request.GET.get('cidade', None)
    nome = request.GET.get('nome', None)
    preco = request.GET.get('preco', None)
    categoria = request.GET.get('categoria', None)
    cidade = Estabelecimento.get_cidade_index(cidade)
    valid_querystring = {k: v for k, v in request.GET.dict().items() if v}
    if valid_querystring != request.GET.dict():
        encoded_querystring = '?' + urllib.parse.urlencode(valid_querystring)
        return HttpResponseRedirect(resolve_url('home') + encoded_querystring)

    parametros = ''
    for item, value in request.GET.dict().items():
        if not item == 'page':
            parametros += '&{}={}'.format(item, value)
    parametros = parametros.replace(' ', '+')
    query_estabelecimento = Estabelecimento.objects.busca(cidade=cidade, nome=nome, preco=preco, categoria=categoria)

    paginator = Paginator(query_estabelecimento, settings.ESTABELECIMENTOS_POR_PAGINA)
    page = request.GET.get('page')
    try:
        query_estabelecimento = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_estabelecimento = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_estabelecimento = paginator.page(paginator.num_pages)

    anuncios = Anuncio.objects.ativos(count=1)

    context = {
        'estabelecimentos': query_estabelecimento,
        'cidades': cidades,
        'categorias': Categoria.objects.all(),
        'parametros': parametros,
        'anuncios': anuncios
    }
    return render(request, 'core/resultado_busca.html', context)


def estabelecimento_detail(request, slug):
    instance = get_object_or_404(Estabelecimento, slug=slug)
    log = request.GET.get('searchlog')
    if log:
        total_hits = instance.search_hits
        instance.search_hits = total_hits + 1
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

    template_to_render = 'core/estabelecimento_detail.html'
    if instance.is_hotel:
        template_to_render = 'core/hotel_detail.html'
    comments = instance.comments
    paginator = Paginator(comments, 6)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)

    initial_data = {
        'content_type': instance.get_content_type,
        'object_id': instance.id,
        'nota': 1
    }
    form = CommentFormWithRate(request.POST or None, initial=initial_data)

    if form.is_valid():
        c_type = form.cleaned_data.get('content_type').lower()
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get('content')
        new_comment = Comment.objects.filter(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
        ).first()
        if new_comment:
            new_comment.content = content_data
            new_comment.save()

        else:
            new_comment = Comment.objects.create(
                user=request.user,
                content_type=content_type,
                object_id=obj_id,
                content=content_data
            )
        nota = form.cleaned_data.get('nota')

        rating = instance.nota.rate(user=request.user, instance=instance, score=int(nota))
        new_comment.aprovado = False
        new_comment.save()
        # if created:
        #     form = CommentForm(None, initial=initial_data)
        #     messages.success(request, _('Seu comentário será moderado e adicionado em breve.'))
        messages.success(request, _('Seu comentário será moderado e adicionado em breve.'))
        form = CommentForm(None, initial=initial_data)

    stars = [i for i in range(1, app_settings.STAR_RATINGS_RANGE + 1)]
    rating = Rating.objects.for_instance(instance)

    context = {
        'estabelecimento': instance,
        'comments': comments,
        'form': form,
        'coordenadas': instance.get_coordenadas,
        'stars': stars,
        'rating': rating,
    }
    return render(request, template_to_render, context)


def categoria_detail(request, slug):
    try:
        categoria = Categoria.objects.get(slug=slug)
    except:
        raise Http404
    query_estabelecimento = Estabelecimento.objects.busca(categoria=categoria.nome)

    paginator = Paginator(query_estabelecimento, settings.ESTABELECIMENTOS_POR_PAGINA)
    page = request.GET.get('page')
    try:
        query_estabelecimento = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_estabelecimento = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_estabelecimento = paginator.page(paginator.num_pages)

    anuncios = Anuncio.objects.ativos(count=1)

    context = {
        'estabelecimentos': query_estabelecimento,
        'categorias': Categoria.objects.all(),
        'anuncios': anuncios
    }
    return render(request, 'core/resultado_busca.html', context)


def categorias(request):
    categorias = Categoria.objects.all()
    return render(request, 'core/categorias.html', {'categorias': categorias})

src/core/templates/posts/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}

{% block  nav %}
    {% include 'nav-interno.html' %}
{% endblock %}


{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title %}
{% block post_detail_link %}
    <li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}


{% block content %}
<main class="main">
        <div class="container">
            <div class="row">
                <div id="post-details">
                    {% include 'core/widgets/messages_display.html' %}
                    <div class="col-xs-12">
                        <div class="breadcrumbs">
                            <nav>
                                <a href="/">
                                    Home
                                </a>
                                <a href="{% url 'noticias:list' %}?t={{ instance.get_type_display }}">
                                    {{ instance.get_type_display }}
                                </a>
                                <a href="{% url 'noticias:detail' slug=instance.slug %}">
                                    {{ instance.title }}
                                </a>
                            </nav>
                        </div>
                    </div>
                    <div class='col-xs-12'>
                        <div class="img" {% if instance.image %} style="background-image:url('{{ instance.image.url }}');" {% endif %}>
                            <div class="title">
                                <small class="date">
                                    {% if instance.draft %}
                                    <span style='color:red;'>Draft</span> 
                                    {% endif %}
                                    <i class="fa fa-calendar"></i>
                                    {{ instance.publish }}
                                </small>
                                <div class="clearfix"></div>
                                <small class="read-time">
                                    <i class="fa fa-clock-o"></i>
                                    {% trans 'Tempo de leitura' %}: {% if instance.read_time <= 1 %} < 1 {% trans 'minuto' %}{% else %}{{ instance.read_time }} {% trans 'minutos' %}{% endif %}
                                </small>
                                <div class="clearfix"></div>
                                <h1>{{ title }}</h1>
                            </div>
                        </div>
                        <p>
                            
                        </p>
                        {% if instance.user.get_full_name %}
                            <p>Author: {{ instance.user.get_full_name }}</p>
                        {% endif %}
                        <p>
                            <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
                            <hr/>
                        </p>    
                    </div>
                    <div class="col-xs-12">
                        <div class="post-detail-item">
                            {{ instance.get_markdown }}
                        </div>
                    </div>   
                </div>
                
            </div>
            

                <!-- <p>
    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
    Facebook
    </a>

    <a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
    Twitter
    </a>

    <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>


    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
    Linkedin
    </a>

    <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ share_string }}.">Reddit</a>

    </p> -->
                <div class='row'>
                    <div class="col-xs-12">
                        {% if comments %}
                            <h3>{% trans 'Comentários' %}</h3>
                            <hr>
                            {% for comment in comments %}
                                <div class="comment">
                                    <div class="user-photo">
                                        {% if comment.user.profile.avatar_normal %}
                                            <img src="{{comment.user.profile.avatar_normal}}" alt="">
                                        {% else %}
                                            <img src="{% static 'img/avatar-holder.png' %}" width="60" alt="">
                                        {% endif %}
                                    </div>
                                    <div class="user-content">
                                        <p class="name">{{ comment.user }}</p>
                                        <p class="date">{{ comment.timestamp|timesince }} atrás</p>
                                        <p class="content">{{ comment.content }}</p>
                                    </div>
                                </div>
                                    <div class="comment-reply">
                                        {% for child_comment in comment.children %}
                                            <blockquote>
                                                <p>{{ child_comment.content }}</p>
                                                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                                            </blockquote>
                                        {% endfor %}
                                        {#                                    {% if request.user.is_authenticated %}#}
                                        {##}
                                        {#                                        <form method="POST">{% csrf_token %}#}
                                        {#                                            {{ comment_form|crispy }}#}
                                        {#                                            <input type="hidden" name="parent_id" value='{{ comment.id }}'>#}
                                        {#                                            <input type="submit" value="Post comment" class="btn btn-default">#}
                                        {#                                        </form>#}
                                        {#                                    {% else %}#}
                                        {#                                        <p>You must log in to comment</p>#}
                                        {#                                    {% endif %}#}
                                    </div>

                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class='col-xs-12'>
                            <h3>{% trans 'Deixe seu comentário' %}</h3>
                            {% if request.user.is_authenticated %}
                                <form method="POST">{% csrf_token %}
                                    {{ comment_form|crispy }}
                                    <div class="pull-right">
                                        <input type="submit" value="{% trans 'Enviar comentário' %}" class="btn btn-primary">
                                    </div>
                                </form>
                            {% else %}
                                <p>{% trans 'Voce precisa estar logado para comentar.' %}</p>
                            {% endif %}
                    </div>
                </div>
            </div>
</main>
 

{% endblock content %}

src/core/templates/posts/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %} {{ form.media }} {% endblock head_extra %}

{% block content %}
    <div class="container">
        <div class="col-sm-6">
            <h1>Preview</h1>
            <div class="content-preview">
                <h3 id="preview-title"></h3>
                <p id="preview-content"></p>
            </div>
        </div>
        <div class='col-sm-6'>
            <h1>Crie um post</h1>

            <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
                {{ form|crispy }}
                <hr>
                <input type='submit' class='btn btn-primary' value='Criar Post' />
            </form>
        </div>
    </div>
    <br>
    <br>


{% endblock content %}
{% block script %}

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function(){
            $(".content-markdown").each(function () {
                var content = $(this).text();
                var markedContent = marked(content);
                $(this).html(markedContent)
            });

            var contentIput = $("#id_content");

            function setContent(value) {
                var markedContent = marked(value);
                $("#preview-content").html(markedContent);
                $("#preview-content img").each(function () {
                    $(this).addClass("img-responsive");
                })

            }

            setContent(contentIput.val());

            contentIput.keyup(function () {
                var newContent = $(this).val();
                console.log('nos');
                setContent(newContent);
            });

            var titleInput = $("#id_title");

            function setTitle(value) {
                $("#preview-title").text(value)
            }
            setTitle(titleInput.val());

            $("#preview-title").text(titleInput.val());
            titleInput.keyup(function () {
                var newTitle = $(this).val();
                setTitle(newTitle)
            });
            $('.comment-reply-btn').click(function (event) {
                event.preventDefault();
                $(this).parent().next(".comment-reply").fadeToggle()
            })


        });
    </script>
{% endblock %}

src/core/templates/posts/post_list.html
{% extends "base.html" %}
{% load i18n %}

{% block  nav %}
    {% include 'nav-interno.html' %}
{% endblock %}

{% block content %}
    <main class="main">
        <div class="container post-list">

            <div class="row">
                <div class="col-xs-12">
                    <div class="breadcrumbs">
                     <nav>
                        <a href="/">
                            Home
                        </a>
                        <a href="{% url 'noticias:list' %}?t={{ tipo }}">
                            {{ tipo }}
                        </a>
                    </nav>
                </div>
                </div>
                <div class="col-xs-8 col-xs-offset-2">
                    {% for obj in object_list %}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="post">
                                    <div class="thumbnail">
                                        {% if obj.image %}
                                            <img src='{{ obj.image.url }}' class='img-responsive' />
                                        {% endif %}
                                        <div class="caption post-detail-item">
                                            <small class="date"> <i class="fa fa-calendar"></i> {{ obj.publish }}</small>
                                            {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
                                            <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a></h3>
                                           
                                            {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
                                            <div class="desc">
                                                {{ obj.get_markdown|truncatechars_html:300 }}<a href="{{ obj.get_absolute_url }}" role="button"> {% trans '+ Leia a matéria completa' %}</a>
                                            </div>
                                        </div>
                                    </div>    
                                </div>
                                
                            </div>
                            <hr/>
                        </div>
                    {% endfor %}
                    <div class="pagination">
                        <span class="step-links">
                            {% if object_list.has_previous %}
                                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><</a>
                            {% endif %}

                            <span class="current">
                                {% trans 'Pagina' %} {{ object_list.number }} {% trans 'de' %} {{ object_list.paginator.num_pages }}.
                            </span>

                            {% if object_list.has_next %}
                                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">></a>
                            {% endif %}
                        </span>
                    </div>
                </div>
                <div class="col-xs-4">
{#                    <form method='GET' action='' class="row">#}
{#                        <div class="col-sm-12">#}
{#                            <div class="input-group">#}
{#                                <input class="form-control" type='text' name='q' placeholder='Procurar Matérias' value='{{ request.GET.q }}'/>#}
{#                                <span class="input-group-btn">#}
{#                                    <button class="btn btn-default" type="button"><i class="fa fa-search"></i> Buscar</button>#}
{#                                </span>#}
{#                            </div>#}
{#                        </div>#}
{#                    </form>#}
                </div>

            </div>
        </div>
    </main>
    
{% endblock content %}