sparaguai/urls.py
from django.conf.urls import url
from django.contrib import admin
from core.views import home, estabelecimento_detail, categoria_detail, busca

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^categoria/(?P<slug>[\w-]+)$', categoria_detail, name='categoria_detail'),
    url(r'^busca/', busca, name='busca'),
    url(r'^admin/', admin.site.urls),
]

src/newsletters/urls.py
from django.conf.urls import url

from src.newsletters.views import create

urlpatterns = [
    url(r'^create/$', create, name='create'),

]

src/posts/urls.py
from django.conf.urls import url

from src.posts.views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from src.core.views import home, estabelecimento_detail, categoria_detail, categorias, busca


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    url(r'^$', home, name='home'),
    url(r'^busca/$', busca, name='busca'),
    url(r'^estabelecimento/(?P<slug>[\w-]+)$', estabelecimento_detail, name='estabelecimento_detail'),
    url(r'^estabelecimento/$', home, name='estabelecimentos'),
    url(r'^categorias/$', categorias, name='categorias'),
    url(r'^api/', include('src.api.urls', namespace='api')),
    url(r'^tickets/', include('src.tickets.urls', namespace='tickets')),
    url(r'^noticia/', include('src.posts.urls', namespace='noticias')),
    url(r'^newsletters/', include('src.newsletters.urls', namespace='newsletters')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^categorias/(?P<slug>[\w-]+)/$', categoria_detail, name='categoria_detail'),

    # url(r'^password/change/$',
    #     auth_views.password_change,
    #     name='password_change'),
    # url(r'^password/change/done/$',
    #     auth_views.password_change_done,
    #     name='password_change_done'),
    # url(r'^password/reset/$',
    #     auth_views.password_reset,
    #     name='password_reset'),
    # url(r'^password/reset/done/$',
    #     auth_views.password_reset_done,
    #     name='password_reset_done'),
    # url(r'^password/reset/complete/$',
    #     auth_views.password_reset_complete,
    #     name='password_reset_complete'),
    # url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     auth_views.password_reset_confirm,
    #     name='password_reset_confirm'),
    # url(r'^accounts/profile/(?P<pk>[0-9]+)/update/$', UserProfileUpdate.as_view(), name='user_profile_update'),
    # url(r'^accounts/profile/(?P<slug>[\w-]+)/$', UserProfileDetail.as_view(), name='user_profile'),
    # url(r'^accounts/profile/$', profile, name='my_user_profile'),
    # url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    # url(r'^accounts/login/$', login, name='auth_login'),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--


    url(r'^admin/', admin.site.urls),

]

core/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

from core.models import Categoria, Estabelecimento


def home(request):
    context = {'nodes': Categoria.objects.all()}
    return render(request, 'index.html', context)


def estabelecimento_detail(request, slug):
    estabelecimento = get_object_or_404(Estabelecimento, slug=slug)
    return render(request, 'core/estabelecimento_detail.html', {'estabelecimento': estabelecimento})


def categoria_detail(request, slug):
    categoria = Categoria.objects.get(slug=slug)
    estabelecimentos = Estabelecimento.objects.filter(categoria=categoria)
    return render(request, 'core/categoria_detail.html', {'categoria': categoria})


def busca(request):
    context = {'estabelecimentos': None}
    if 's' in request.GET:
        context = {'estabelecimentos': Estabelecimento.objects.filter(nome__icontains=request.GET['s'])}

    return render(request, 'core/busca_resultado.html', context)

src/core/views.py
import urllib

from django.conf import settings
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, resolve_url
from django.utils.translation import ugettext as _
from star_ratings import app_settings
from star_ratings.models import Rating

from src.comments.forms import CommentForm, CommentFormWithRate
from src.comments.models import Comment
from src.core.models import Categoria, Estabelecimento, Anuncio
from src.posts.models import Post


def home(request):

    query_estabelecimento = Estabelecimento.objects.all()

    noticias = Post.objects.noticias().principais(2)
    lazer = Post.objects.lazer().principais(4)

    recomendados = Estabelecimento.objects.recomendados(12)

    mais_buscados = Estabelecimento.objects.mais_buscados(32)
    mais_buscados_recomendados = Estabelecimento.objects.mais_buscados().recomendados(8)
    anuncios = Anuncio.objects.ativos(2)

    categorias = Categoria.objects.recomendadas(6)

    context = {
        'estabelecimentos': query_estabelecimento,
        'noticias': noticias,
        'lazer': lazer,
        'recomendados': recomendados,
        'anuncios': anuncios,
        'mais_buscados': mais_buscados,
        'mais_buscados_recomendados': mais_buscados_recomendados,
        'categorias': categorias
    }
    return render(request, 'index.html', context)


def busca(request):
    cidades = [cidade[1] for cidade in Estabelecimento.CIDADES]

    cidade = request.GET.get('cidade', None)
    nome = request.GET.get('nome', None)
    preco = request.GET.get('preco', None)
    categoria = request.GET.get('categoria', None)
    cidade = Estabelecimento.get_cidade_index(cidade)
    valid_querystring = {k: v for k, v in request.GET.dict().items() if v}
    if valid_querystring != request.GET.dict():
        encoded_querystring = '?' + urllib.parse.urlencode(valid_querystring)
        return HttpResponseRedirect(resolve_url('home') + encoded_querystring)

    parametros = ''
    for item, value in request.GET.dict().items():
        if not item == 'page':
            parametros += '&{}={}'.format(item, value)
    parametros = parametros.replace(' ', '+')
    query_estabelecimento = Estabelecimento.objects.busca(cidade=cidade, nome=nome, preco=preco, categoria=categoria)

    paginator = Paginator(query_estabelecimento, settings.ESTABELECIMENTOS_POR_PAGINA)
    page = request.GET.get('page')
    try:
        query_estabelecimento = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_estabelecimento = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_estabelecimento = paginator.page(paginator.num_pages)

    anuncios = Anuncio.objects.ativos(count=1)

    context = {
        'estabelecimentos': query_estabelecimento,
        'cidades': cidades,
        'categorias': Categoria.objects.all(),
        'parametros': parametros,
        'anuncios': anuncios
    }
    return render(request, 'core/resultado_busca.html', context)


def estabelecimento_detail(request, slug):
    instance = get_object_or_404(Estabelecimento, slug=slug)
    log = request.GET.get('searchlog')
    if log:
        total_hits = instance.search_hits
        instance.search_hits = total_hits + 1
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

    template_to_render = 'core/estabelecimento_detail.html'
    if instance.is_hotel:
        template_to_render = 'core/hotel_detail.html'
    comments = instance.comments
    paginator = Paginator(comments, 6)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)

    initial_data = {
        'content_type': instance.get_content_type,
        'object_id': instance.id,
        'nota': 1
    }
    form = CommentFormWithRate(request.POST or None, initial=initial_data)

    if form.is_valid():
        c_type = form.cleaned_data.get('content_type').lower()
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get('content')
        new_comment = Comment.objects.filter(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
        ).first()
        if new_comment:
            new_comment.content = content_data
            new_comment.save()

        else:
            new_comment = Comment.objects.create(
                user=request.user,
                content_type=content_type,
                object_id=obj_id,
                content=content_data
            )
        nota = form.cleaned_data.get('nota')

        rating = instance.nota.rate(user=request.user, instance=instance, score=int(nota))
        new_comment.aprovado = False
        new_comment.save()
        # if created:
        #     form = CommentForm(None, initial=initial_data)
        #     messages.success(request, _('Seu comentário será moderado e adicionado em breve.'))
        messages.success(request, _('Seu comentário será moderado e adicionado em breve.'))
        form = CommentForm(None, initial=initial_data)

    stars = [i for i in range(1, app_settings.STAR_RATINGS_RANGE + 1)]
    rating = Rating.objects.for_instance(instance)

    context = {
        'estabelecimento': instance,
        'comments': comments,
        'form': form,
        'coordenadas': instance.get_coordenadas,
        'stars': stars,
        'rating': rating,
    }
    return render(request, template_to_render, context)


def categoria_detail(request, slug):
    try:
        categoria = Categoria.objects.get(slug=slug)
    except:
        raise Http404
    query_estabelecimento = Estabelecimento.objects.busca(categoria=categoria.nome)

    paginator = Paginator(query_estabelecimento, settings.ESTABELECIMENTOS_POR_PAGINA)
    page = request.GET.get('page')
    try:
        query_estabelecimento = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_estabelecimento = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_estabelecimento = paginator.page(paginator.num_pages)

    anuncios = Anuncio.objects.ativos(count=1)

    context = {
        'estabelecimentos': query_estabelecimento,
        'categorias': Categoria.objects.all(),
        'anuncios': anuncios
    }
    return render(request, 'core/resultado_busca.html', context)


def categorias(request):
    categorias = Categoria.objects.all()
    return render(request, 'core/categorias.html', {'categorias': categorias})

src/core/templates/base.html
{% load static %}
{% load bootstrap3 %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Guia Paraguai{% endblock %}</title>
    <meta name="description" content="{% block pagedesc %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/normalize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    {% block css %} {% endblock %}
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>
<body>
{% block  nav %}
{% endblock %}

{% block content %}
{% endblock %}

<footer class="footer">
    {% block footer %}
        {% include 'footer.html' %}
    {% endblock %}
</footer>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"><script>' )</script>
<script src="{% static 'js/vendor/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery.simpleWeather.min.js' %}"></script>

{% block script %}
{% endblock %}
<script src="{% static 'js/main.js' %}"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>
</body>
</html>

src/core/templates/footer.html
{% load static %}
{% load i18n %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <img src="{% static 'img/logo-footer.png' %}" width="100%" alt="" class="">
        </div>
        <div class="col-md-9">
            <div class="pull-right">
                <div class="social">
                    <span>{% trans 'Siga-nos em nossas redes sociais:' %} </span>
                    <div class="pull-right">
                        <nav>
                            <a href="#">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-instagram"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-twitter">
                                </i>
                            </a>
                        </nav>    
                    </div>
                        
                </div>
                
            </div>
            <div class="clearfix"></div>
            <div class="newsletter">
                <form id='mainSearch' action="{% url 'newsletters:create' %}">
                <button type="submit">{% trans 'Cadastrar' %}</button>
                    <span>
                        <input type="search" placeholder="{% trans 'Cadastre-se e receba tudo sobre o Paraguai e Região' %}" name="email">
                    </span>
                </form>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<div class="end">
    {% trans 'Guia Paraguai - 2017 - Todos os direitos Reservados' %}
</div>

src/core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block  nav %}
    {% include 'nav-index.html' %}
{% endblock %}

{% block content %}
    <div class="text-center">
    </div>

    <main class="main">
        <div class="info">
            <div class="container">
                <h3 class="title text-center">
                    {% trans 'O Guia Paraguai <b>é a sua referência</b> na fronteira' %}
                </h3>
                <div class="col-md-3">
                    <div class="info-box">
                        <i class="icon person"></i>
                        <h3>5 {% trans 'mil' %}</h3>
                        {% trans 'de locais cadastrados' %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info-box">
                        <i class="icon bubble"></i>
                        <h3>20 {% trans 'mil' %}</h3>
                        {% trans 'de avaliações e opniões' %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info-box">
                        <i class="icon heart"></i>
                        <h3>500 {% trans 'mil' %}</h3>
                        {% trans 'de visitantes mensais' %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info-box">
                        <i class="icon seek"></i>
                        <h3>2 {% trans 'milhões' %}</h3>
                        {% trans 'de locais buscados' %}
                    </div>
                </div>
            </div>
        </div>


        <div class="places">
            <h3><b>{% trans 'Lugares' %}</b> {% trans 'mais visitados' %}</h3>
            <h4>{% trans 'Lugares mais buscados pelos clientes no primeiro trimestre de 2017' %}</h4>
            <div class="itens owl-carousel owl-theme">
                {% include 'core/widgets/estabelecimento_card.html' with estabelecimentos=mais_buscados %}
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <div class="container" style='margin-top:40px;'>
            <div class="row">
                <div class="col-md-8">
                    <h3 class="title hasborder">{% trans 'Locais mais <b>buscados</b>' %}</h3>
                    <nav class="top-search">
                        {% for e in mais_buscados %}
                            <a href="{{ e.get_absolute_url }}">{{ e.nome }}</a>
                        {% endfor %}
                    </nav>
                </div>
                <div class="col-md-4">
                    <div class="boxed">
                        <h3 class="title">{% trans 'Guia Paraguai <b>Recomenda</b>' %}</h3>
                    </div>
                    <div class="boxed">
                        <ul class="recommend-list">
                            {% for e in mais_buscados_recomendados %}
                                <li>
                                    <a href="{{ e.get_absolute_url }}" class="img">
                                        <img src="{{ e.logo.url }}" width="90%" alt="{{ e.nome }}">
                                    </a>
                                    <a href="{{ e.get_absolute_url }}" class="desc">
                                        <h3>{{ e.nome }}</h3>
                                        <span class="clearfix"></span>
                                        <h4>{{ e.descricao|truncatechars_html:60 }}</h4>
                                    </a>
                                    <div class="clearfix"></div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h3 class="title hasborder">{% trans 'Principais <b>Noticias</b>' %}</h3>
                </div>
                {% for noticia in noticias %}
                    <div class="col-md-6">
                        <div class="news">
                            <a href="{{ noticia.get_absolute_url }}">
                                <img src="{{ noticia.image.url }}" width="100%" alt="">
                                <h4 class="title">{{ noticia.title }}</h4>
                                <p>{{ noticia.get_markdown|truncatechars_html:120 }}</p>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="places text-center">
            <div class="container">
                <h3>
                    {% trans 'Turismo e <b>Lazer</b>' %}
                </h3>
                <h4>{% trans 'Os principais pontos turisticos do Paraguay e região' %}</h4>
                <div class="row">
                    {% for post in lazer %}
                        <div class="col-md-3">
                            <img src="{{ post.image.url }}" width="100%" alt="">
                            <p class="title">{{ post.title }}</p>
                            <div class="desc">
                                {{ post.get_markdown|truncatechars_html:120 }}
                            </div>
                            <a href="{{ post.get_absolute_url }}" class="btn pull-right">Leia mais</a>
                        </div>
                    {% endfor %}
                </div>
                <div class="clearfix"></div>
                <div class="banners">
                    <div class="row">
                        {% for anuncio in anuncios %}
                            <div class="col-md-6">
                                <a href="{{ anuncio.url }}">
                                    <img src="{{ anuncio.banner.url }}" width="100%" alt="">
                                </a>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </main>
{% endblock %}

src/core/templates/nav-index.html
{% load static %}
{% load i18n %}
<!--[if lt IE 8]>
    <p class="browserupgrade">Notamos que você está utilizando um navegador <strong>desatualizado</strong>. Por favor <a href="http://browsehappy.com/">atualize seu navegador</a> para melhorar sua experiência.</p>
    <![endif]-->

<header class="header">
    <div class="container">
        <div class="row">
            {% include 'core/widgets/nav-base.html' %}
            <div class="col-xs-12">
                <a href="#" class="logo">
                    <img src="{% static 'img/logo.png' %}" width="400" alt="">
                </a>
                <div class="clearfix"></div>
            </div>
            <div class="col-xs-12">
                <div class="main-search">
                    <div class="search">
                        <form id='mainSearch' action="{% url 'busca' %}">
                            <button type="submit">{% trans 'Buscar' %}</button>
                            <span>
                                <input type="search" placeholder="{% trans 'Encontre: Restaurantes, Bares, Hotéis e etc' %}" name="nome">        
                            </span>
                        </form>

                        <div class="clearfix"></div>
                    </div>

                </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-xs-12">
                <div class="main-nav">
                    <nav>
                        {% if categorias %}
                            {% for c in categorias %}
                                <a href="{{ c.get_absolute_url }}">{{ c.nome }}</a>
                            {% endfor %}
                        {% else %}
                            <a href="#">Restaurantes</a>
                            <a href="#">Bares</a>
                            <a href="#">Atrações</a>
                            <a href="#">Lojas</a>
                            <a href="#">Comidinhas</a>
                            <a href="#">Hotéis</a>
                        {% endif %}
                        <a href="{% url 'noticias:list' %}?t=noticia">{% trans 'Noticias' %}</a>
                        <a href="{% url 'noticias:list' %}?t=lazer">{% trans 'Lazer / Turismo' %}</a>
                        <a href="{% url 'categorias' %}">{% trans 'Mais categorias' %}</a>
                    </nav>
                </div>
            </div>

        </div>
    </div>
</header>

src/core/templates/nav-interno.html
{% load static %}
{% load i18n %}
<header class="header intern">

    {% include 'core/widgets/nav-base.html' %}
    <div class="abovebar">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <a href="/">
                        <img src="{% static 'img/logo-interna.png' %}" width="78%" alt="">
                    </a>
                </div>
                <div class="col-md-8">
                    <div class="main-search">
                        <div class="search">
                            <form id='mainSearch' action="{% url 'busca' %}">
                                <button type="submit">{% trans 'Buscar' %}</button>
                                <span>
                                    <input type="search" placeholder="{% trans 'Encontre: Restaurantes, Bares, Hotéis e etc' %}" name="nome">        
                                </span>
                            </form>

                            <div class="clearfix"></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>        
</header>